version: '3'

services:
  geddit-api:
    image: geddit-api
    ports:
      - "8080:8080"
    depends_on:
      - geddit-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://geddit-db:5432/geddit
      SPRING_DATASOURCE_USERNAME: your-db-username
      SPRING_DATASOURCE_PASSWORD: your-db-password

  geddit-db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: your-database-name
      POSTGRES_USER: your-db-username
      POSTGRES_PASSWORD: your-db-password
