server:
  servlet:
    context-path: /geddit/api

spring:
  profiles:
    active: dev
    datasource:
      url: ${SPRING_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        jdbc.batch_size: 30
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
logging:
  level:
    web: info
springdoc:
  api-docs:
    path: /swagger/api-docs
  swagger-ui:
    path: /swagger/swagger-ui.html