spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/geddit
    username: postgres
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        jdbc.batch_size: 30
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
#logging:
#  level:
#    web: info
springdoc:
  api-docs:
    path: /swagger/api-docs
  swagger-ui:
    path: /swagger/swagger-ui.html

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days